extends RefCounted

static func item(id: int, count: int = 1, data: Dictionary = {}) -> Dictionary:
	var result: Dictionary = {"id":id,"count":count,"wear":0}
	if not data.is_empty(): result["data"] = data.duplicate(true)
	return result

static func run(suite: SceneTree, game: Node3D) -> void:
	for id in PortableStorage.BLOCKS:
		suite.check(Nodes.exists(id) and Nodes.placeable(id),"storage block %d is registered and placeable"%id)
	suite.check(Nodes.max_stack(PortableStorage.SHULKER_PURPLE) == 1 and Nodes.max_stack(PortableStorage.ENDER_CHEST) == 64,"shulker boxes are single items while Ender chests stack")
	suite.check(Nodes.harvestable(PortableStorage.SHULKER_PURPLE,0) and not Nodes.harvestable(PortableStorage.ENDER_CHEST,0),"shulker boxes can be recovered by hand; Ender chests need a pickaxe")
	var inv := Inventory.new()
	inv.add_item(Nodes.OBSIDIAN,8); inv.add_item(Nodes.ENDER_EYE)
	suite.check(inv.craft(inv.recipe_index(PortableStorage.ENDER_CHEST),"table") and inv.count_item(PortableStorage.ENDER_CHEST) == 1 and inv.count_item(Nodes.OBSIDIAN) == 0,"eight obsidian and an Eye of Ender craft one Ender chest")
	inv = Inventory.new(); inv.add_item(Nodes.SHULKER_SHELL,2); inv.add_item(Nodes.CHEST)
	suite.check(inv.craft(inv.recipe_index(PortableStorage.SHULKER_PURPLE),"table") and inv.count_item(PortableStorage.SHULKER_PURPLE) == 1,"two existing shulker shells and a chest craft the purple box")

	var book: Dictionary = item(Nodes.WRITTEN_BOOK,1,{"title":"Voyage","text":"Cargo reaches the outer islands.","custom_name":"Captain's log"})
	var tool: Dictionary = item(95,1,{"enchantments":{"Silk Touch":1,"Mending":1},"custom_name":"Deep explorer"}); tool.wear = 133
	var cargo: Array = PortableStorage.clean_contents([]); cargo[0] = book; cargo[10] = item(Pouches.SINGLE); cargo[26] = tool
	var box: Dictionary = item(PortableStorage.SHULKER_PURPLE,1,{"contents":cargo,"custom_name":"Expedition supplies"})
	var restored: Dictionary = Inventory.clean_slot(JSON.parse_string(JSON.stringify(box)))
	suite.check(restored == box and restored.data.contents.size() == 27,"JSON restoration preserves all 27 shulker slots, names, books, enchantments and tool wear")
	var invalid: Array = PortableStorage.clean_contents([item(PortableStorage.SHULKER_BASE),item(Nodes.DIAMOND,99),"invalid"])
	suite.check(invalid[0].id == 0 and invalid[1].count == 64 and invalid[2].id == 0,"shulker loading removes nested boxes and malformed slots and clamps stacks")
	var pouch: Dictionary = item(Pouches.SINGLE,1,{"contents":[item(PortableStorage.SHULKER_PURPLE)]})
	suite.check(not PortableStorage.accepts({"kind":"shulker"},pouch) and not PortableStorage.accepts({"kind":"shulker"},box),"a shulker rejects boxes both directly and hidden inside pouches")
	var hidden: Array = PortableStorage.clean_contents([pouch])
	suite.check(hidden[0].id == Pouches.SINGLE and hidden[0].data.contents[0].id == 0,"save restoration cannot sneak a nested shulker through a pouch")
	var box_with_pouch: Dictionary = item(PortableStorage.SHULKER_PURPLE,1,{"contents":[item(Pouches.SINGLE)]})
	suite.check(not PortableStorage.accepts({"kind":"pouch"},box_with_pouch),"a pouch cannot recursively hold itself through a shulker box")
	suite.check(PortableStorage.accepts({"kind":"shulker"},book) and PortableStorage.accepts({"kind":"ender"},box),"ordinary cargo enters shulkers and full shulkers enter personal Ender storage")
	inv = Inventory.new(); inv.exchange_pouch(0,item(Pouches.SINGLE))
	for i in Inventory.BASE_SLOTS: inv.slots[i] = item(Nodes.COBBLE,64)
	suite.check(inv.capacity(box.id,0,box.data) == 0 and inv.add_item(box.id,1,0,box.data) == 1 and inv.slots[36].id == 0,"pickup cannot place a box holding even an empty pouch into equipped pouch pages")
	inv = Inventory.new(); inv.grid[0] = box.duplicate(true); inv.grid[1] = item(VillageContent.DYE_RED)
	var recolored: Dictionary = inv.take_grid_result("hand")
	suite.check(not recolored.is_empty() and recolored.id == PortableStorage.SHULKER_BASE+6 and recolored.get("data",{}) == box.data,"dyeing a loaded box preserves cargo and its custom name")
	inv.grid[0] = recolored.duplicate(true); inv.grid[1] = item(VillageContent.DYE_BLUE)
	var blue: Dictionary = inv.take_grid_result("hand")
	suite.check(not blue.is_empty() and blue.id == PortableStorage.SHULKER_BASE+9 and blue.get("data",{}) == box.data,"any colored box can be dyed again without requiring the purple variant")

	game.pause(); game.gamemode = "survival"; game.inventory.selected = 0
	var p: Vector3i = Vector3i(game.player.position.floor())+Vector3i(3,3,3)
	for x in range(-1,4):
		for z in range(-1,2):
			game.world.set_node(p+Vector3i(x,-1,z),Nodes.STONE)
			for y in range(3): game.world.set_node(p+Vector3i(x,y,z),Nodes.AIR)
	game.inventory.slots[0] = box.duplicate(true)
	game.world.set_node(p,box.id); PortableStorage.placed(game,p,game.inventory.held())
	game.inventory.held().data.contents[0].data.text = "Changed only in the item"
	var placed: Dictionary = PortableStorage.station(game.world,p)
	suite.check(placed.slots[0] == book and placed.slots[10].id == Pouches.SINGLE and placed.slots[26] == tool,"placement copies independent cargo, including an empty pouch, into the block's inventory")
	PortableStorage.interact(game,p)
	game.hud.cursor = item(PortableStorage.SHULKER_BASE)
	game.hud._slot_click(2,true,false)
	suite.check(placed.slots[2].id == 0 and game.hud.cursor.id == PortableStorage.SHULKER_BASE,"mouse insertion cannot put a box inside an open shulker")
	game.hud.cursor = pouch.duplicate(true); game.hud._slot_click(2,true,false)
	suite.check(placed.slots[2].id == 0 and game.hud.cursor.id == Pouches.SINGLE,"mouse insertion cannot hide a nested box inside a pouch")
	game.hud.cursor = item(0,0); game.inventory.slots[1] = pouch.duplicate(true)
	game.hud.shift_mode = true; game.hud._slot_click(1,false,false); game.hud.shift_mode = false
	suite.check(game.inventory.slots[1].id == Pouches.SINGLE and placed.slots[2].id == 0,"shift transfer also rejects an indirectly nested box")
	game.pause()
	var q: Vector3i = p+Vector3i.RIGHT
	game.world.set_node(q,Nodes.HOPPER); game.world.circuits.configure(q,Vector3i.LEFT)
	var hopper: Array = game.world.circuits.container(q); hopper[0] = pouch.duplicate(true)
	game.world.circuits.hopper(q)
	suite.check(hopper[0].count == 1 and placed.slots[2].id == 0,"hopper insertion rejects a pouch containing another shulker")
	hopper[0] = item(PortableStorage.SHULKER_BASE); game.world.circuits.hopper(q)
	suite.check(hopper[0].count == 1,"hopper insertion rejects a directly nested shulker")
	hopper[0] = item(Nodes.DIAMOND,2); game.world.circuits.hopper(q)
	suite.check(hopper[0].count == 1 and placed.slots[1].id == Nodes.DIAMOND,"hopper insertion still transfers ordinary cargo into a shulker")
	game.world.stations.erase(VoxelWorld.station_key(q)); game.world.set_node(q,Nodes.DROPPER)
	game.world.circuits.configure(q,Vector3i.LEFT)
	var dropper: Array = game.world.circuits.container(q); dropper[0] = pouch.duplicate(true)
	game.world.circuits.dispense(q,false)
	suite.check(dropper[0].count == 1 and placed.slots[2].id == 0,"dropper insertion rejects indirectly nested shulkers without consuming them")
	dropper[0] = item(Nodes.DIAMOND,2); game.world.circuits.dispense(q,false)
	suite.check(dropper[0].count == 1 and placed.slots[1].count == 2,"dropper insertion preserves the ordinary container transfer path")
	game.world.stations.erase(VoxelWorld.station_key(q)); game.world.set_node(q,Nodes.AIR)
	placed.slots[1] = item(Nodes.DIAMOND,11)
	game.world.set_node(q,Nodes.COMPARATOR); game.world.circuits.configure(q,Vector3i.RIGHT)
	var expected_signal: int = game.world.circuits.container_signal(p)
	game.world.circuits.step()
	suite.check(expected_signal > 0 and game.world.circuits.output(q,Vector3i.RIGHT) == expected_signal,"an actual comparator circuit reads a loaded shulker's fullness")
	var preserved_slots: Array = placed.slots
	placed.slots = PortableStorage.clean_contents([]); game.world.circuits.step()
	suite.check(game.world.circuits.output(q,Vector3i.RIGHT) == 0,"the comparator switches off when its shulker becomes empty")
	placed.slots = preserved_slots; game.world.set_node(q,Nodes.AIR)
	game._arrival_set_node(p,Nodes.AIR); game._arrival_set_node(p,Nodes.OBSIDIAN)
	suite.check(game.world.node_at(p) == box.id and PortableStorage.station(game.world,p).slots[26] == tool,"dimension arrival clearing and platform construction preserve a placed shulker and cargo")
	placed.slots[2] = box.duplicate(true); placed.slots[3] = pouch.duplicate(true); placed.slots.append(item(Nodes.DIAMOND,64))
	game._clean_station_storage()
	suite.check(placed.slots.size() == 27 and placed.slots[2].id == 0 and placed.slots[3].id == Pouches.SINGLE and placed.slots[3].data.contents[0].id == 0 and placed.slots[26] == tool,"loaded shulker stations discard excess or recursive cargo and retain valid metadata")
	var before: int = game.drops.get_child_count()
	game.break_node(p,box.id,0)
	suite.check(game.world.node_at(p) == Nodes.AIR and game.drops.get_child_count() == before+1 and not game.world.stations.has(VoxelWorld.station_key(p)),"breaking a loaded shulker emits exactly one item and removes its station")
	var dropped: Node3D = game.drops.get_child(game.drops.get_child_count()-1)
	suite.check(dropped.item_id == box.id and dropped.data.contents[0] == book and dropped.data.contents[1].count == 11 and dropped.data.contents[26] == tool,"the recovered box includes its edited cargo without loose-item duplication")

	game.gamemode = "creative"
	game.inventory.slots[0] = box.duplicate(true)
	game.world.set_node(p,box.id); PortableStorage.placed(game,p,game.inventory.held())
	suite.check(game.inventory.held().id == 0,"creative placement consumes a loaded box so cargo cannot be duplicated")
	before = game.drops.get_child_count(); game.break_node(p,box.id,0)
	suite.check(game.drops.get_child_count() == before+1,"creative breaking preserves a box that contains cargo")
	game.world.set_node(p,box.id); PortableStorage.placed(game,p,item(box.id))
	before = game.drops.get_child_count(); game.break_node(p,box.id,0)
	suite.check(game.drops.get_child_count() == before,"creative breaking of an empty box does not create an extra item")
	game.gamemode = "survival"
	game.world.set_node(p,box.id); PortableStorage.placed(game,p,box)
	before = game.drops.get_child_count(); PortableStorage.break_node(game,p,box.id,0,true)
	suite.check(game.drops.get_child_count() == before+1 and game.drops.get_child(before).data.contents[26] == tool,"explosion destruction keeps shulker contents in one packed drop")

	game.ender_storage = PortableStorage.new_ender_station()
	game.world.set_node(p,PortableStorage.ENDER_CHEST)
	game.world.set_node(p+Vector3i.RIGHT*2,PortableStorage.ENDER_CHEST)
	game._arrival_set_node(p,Nodes.AIR)
	suite.check(game.world.node_at(p) == PortableStorage.ENDER_CHEST,"dimension arrival clearing also preserves Ender chest access blocks")
	PortableStorage.interact(game,p); game.hud.station_data.slots[0] = box.duplicate(true)
	game.pause(); PortableStorage.interact(game,p+Vector3i.RIGHT*2)
	suite.check(game.hud.station_data.slots[0] == box and not game.world.stations.has(VoxelWorld.station_key(p)),"separate Ender chests expose one personal inventory without per-block cargo")
	game.pause(); game.world.set_node(p+Vector3i.UP,Nodes.STONE); PortableStorage.interact(game,p)
	suite.check(game.state == "paused","an opaque block above an Ender chest prevents opening it")
	game.world.set_node(p+Vector3i.UP,Nodes.GLASS); PortableStorage.interact(game,p)
	suite.check(game.state == "inventory" and game.hud.station_data.slots[0] == box,"transparent glass above an Ender chest still permits opening")
	game.pause()
	game.world.set_node(p+Vector3i.UP,Nodes.AIR)
	game.inventory.slots[0] = item(95)
	before = game.drops.get_child_count(); game.break_node(p,PortableStorage.ENDER_CHEST,95)
	var obsidian: Node3D = game.drops.get_child(game.drops.get_child_count()-1)
	suite.check(game.drops.get_child_count() == before+1 and obsidian.item_id == Nodes.OBSIDIAN and obsidian.amount == 8 and game.ender_storage.slots[0] == box,"ordinary pickaxe digging returns eight obsidian while personal cargo remains safe")
	game.inventory.slots[0] = tool.duplicate(true)
	before = game.drops.get_child_count(); game.break_node(p+Vector3i.RIGHT*2,PortableStorage.ENDER_CHEST,95)
	suite.check(game.drops.get_child_count() == before+1 and game.drops.get_child(before).item_id == PortableStorage.ENDER_CHEST,"Silk Touch returns the Ender chest itself")
	var loaded_ender: Dictionary = PortableStorage.new_ender_station(JSON.parse_string(JSON.stringify(game.ender_storage)))
	suite.check(loaded_ender.slots[0] == box and loaded_ender.slots.size() == 27,"personal Ender storage survives a JSON save including portable box contents")
	game.pause()
	var path: String = OS.get_cache_dir().path_join("voxey-storage-check-%d.json"%OS.get_process_id())
	var saved: bool = game.save_game(path)
	var data: Dictionary = game.read_save(path)
	var saved_ender: Dictionary = PortableStorage.new_ender_station(data.get("ender_storage",{}))
	suite.check(saved and data.get("ender_storage",{}).get("slots",[]).size() == 27 and saved_ender.slots[0] == box,"the world save persists personal Ender inventory outside dimension stations")
	for suffix in ["",".bak",".tmp"]:
		if FileAccess.file_exists(path+suffix): DirAccess.remove_absolute(path+suffix)
