#!/usr/bin/env python3
"""Build Voxey's numeric ore rules from the supplied Mineclonia Lua definitions."""
import json, re, subprocess
from pathlib import Path
root='/home/impulse/.minetest/games/mineclonia'
raw=json.loads(subprocess.check_output(['lua','tools/export_mineclonia_ores.lua',root]))
names={'mcl_core:stone':'Nodes.STONE','mcl_core:diorite':'VillageContent.DIORITE','mcl_core:andesite':'VillageContent.ANDESITE','mcl_core:granite':'VillageContent.GRANITE','mcl_deepslate:deepslate':'Nodes.DEEPSLATE','mcl_deepslate:tuff':'MinecloniaOres.TUFF','mcl_nether:netherrack':'Nodes.NETHERRACK','mcl_blackstone:blackstone':'MinecloniaOres.BLACKSTONE','mcl_blackstone:basalt':'Nodes.BASALT','mcl_nether:ancient_debris':'Netherite.ANCIENT_DEBRIS'}
for kind in ['coal','iron','copper','gold','diamond','lapis','redstone','emerald']:
 for host in ['stone','deepslate']:
  prefix='mcl_deepslate' if host=='deepslate' else ('mcl_copper' if kind=='copper' else 'mcl_core')
  names[f'{prefix}:{host}_with_{kind}']=('VillageContent.' if kind=='emerald' else 'Nodes.')+('DEEP_' if host=='deepslate' else '')+kind.upper()+'_ORE'
rules=[]
for row in raw:
 if row['ore_type']!='scatter' or row['ore'] not in names or not ('with_' in row['ore'] or 'ancient_debris' in row['ore']):continue
 hosts=row['wherein'];hosts=[hosts] if isinstance(hosts,str) else hosts
 nether=row['ore'].startswith('mcl_nether:')
 rules.append({'id':names[row['ore']], 'hosts':[names[x] for x in hosts], 'dimension':'nether' if nether else 'overworld','scarcity':row['clust_scarcity'],'count':row['clust_num_ores'],'size':row['clust_size'],'min':row['y_min']+(29067 if nether else 0),'max':row['y_max']+(29067 if nether else 0),'biomes':row.get('biomes',[]),'source':row['ore']})
for ore,scarcity,count,size in [('Nodes.NETHER_QUARTZ_ORE',850,4,3),('Nodes.NETHER_QUARTZ_ORE',1650,8,4),('MinecloniaOres.NETHER_GOLD',830,5,3),('MinecloniaOres.NETHER_GOLD',1660,4,2)]:
 rules.append({'id':ore,'hosts':['Nodes.NETHERRACK'],'dimension':'nether','scarcity':scarcity,'count':count,'size':size,'min':0,'max':128,'biomes':[],'source':'mcl_biomes/init.lua'})
rules.sort(key=lambda r:(r['dimension'],r['id'],r['min'],r['max'],r['scarcity'],r['size'],str(r['biomes'])))
text='class_name MinecloniaOreRules\nextends RefCounted\n\n# Generated by tools/build_ore_catalog.py. Source: Mineclonia mcl_biomes (GPL-3.0).\n# Legacy v7 preset: source cluster sizes, scarcity, host nodes, height and biome restrictions.\nconst DATA = [\n'
for row in rules:
 line=json.dumps(row,separators=(',',':'))
 line=re.sub(r'"((?:Nodes|VillageContent|Netherite|MinecloniaOres)\.[A-Z_]+)"',r'\1',line)
 text+='\t'+line+',\n'
Path('scripts/mineclonia_ore_rules.gd').write_text(text+']\n')
print(f'Exported {len(rules)} ore rules.')
